### ISSUE TITLE
java usage visualization failing in prod

### ISSUE THREAD

**Issue by sjungling** [moderneinc/moderne-visualizations-misc#66]
```Unexpected failure in visualization run: java.io.IOException: Input Notebook:  /app/.virtual_environments/moderne-visualizations-misc/lib/python3.11/site-packages/moderne_visualizations_misc/java_versions_in_use.ipynb
Output Notebook: /home/jovyan/.moderne/notebooks/SZ6O2xjGL.ipynb
Working directory: /app/.virtual_environments/moderne-visualizations-misc/lib/python3.11/site-packages/moderne_visualizations_misc

Executing:   0%|          | 0/4 [00:00&lt;?, ?cell/s]Executing notebook with kernel: python3

Executing:  25%|██▌       | 1/4 [00:01&lt;00:03,  1.14s/cell]
Executing:  50%|█████     | 2/4 [00:01&lt;00:01,  1.14cell/s]
Executing:  50%|█████     | 2/4 [00:02&lt;00:02,  1.13s/cell]
Traceback (most recent call last):
  File "&lt;frozen runpy&gt;", line 198, in _run_module_as_main
  File "&lt;frozen runpy&gt;", line 88, in _run_code
  File "/opt/conda/lib/python3.11/site-packages/papermill/__main__.py", line 4, in &lt;module&gt;
    papermill()
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/papermill/cli.py", line 235, in papermill
    execute_notebook(
  File "/opt/conda/lib/python3.11/site-packages/papermill/execute.py", line 131, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/opt/conda/lib/python3.11/site-packages/papermill/execute.py", line 251, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [2]":
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[2], line 1
----&gt; 1 data = df.drop(
      2     columns=[
      3         "repositoryOrigin",
      4         "repositoryPath",
      5         "repositoryBranch",
      6         "scmType",
      7         "repositoryLink",
      8         "targetVersion",
      9     ]
     10 )
     11 data

File /app/.virtual_environments/moderne-visualizations-misc/lib/python3.11/site-packages/pandas/core/frame.py:5258, in DataFrame.drop(self, labels, axis, index, columns, level, inplace, errors)
   5110 def drop(
   5111     self,
   5112     labels: IndexLabel = None,
   (...)
   5119     errors: IgnoreRaise = "raise",
   5120 ) -&gt; DataFrame | None:
   5121     """
   5122     Drop specified labels from rows or columns.
   5123 
   (...)
   5256             weight  1.0     0.8
   5257     """
-&gt; 5258     return super().drop(
   5259         labels=labels,
   5260         axis=axis,
   5261         index=index,
   5262         columns=columns,
   5263         level=level,
   5264         inplace=inplace,
   5265         errors=errors,
   5266     )

File /app/.virtual_environments/moderne-visualizations-misc/lib/python3.11/site-packages/pandas/core/generic.py:4549, in NDFrame.drop(self, labels, axis, index, columns, level, inplace, errors)
   4547 for axis, labels in axes.items():
   4548     if labels is not None:
-&gt; 4549         obj = obj._drop_axis(labels, axis, level=level, errors=errors)
   4551 if inplace:
   4552     self._update_inplace(obj)

File /app/.virtual_environments/moderne-visualizations-misc/lib/python3.11/site-packages/pandas/core/generic.py:4591, in NDFrame._drop_axis(self, labels, axis, level, errors, only_slice)
   4589         new_axis = axis.drop(labels, level=level, errors=errors)
   4590     else:
-&gt; 4591         new_axis = axis.drop(labels, errors=errors)
   4592     indexer = axis.get_indexer(new_axis)
   4594 # Case for non-unique axis
   4595 else:

File /app/.virtual_environments/moderne-visualizations-misc/lib/python3.11/site-packages/pandas/core/indexes/base.py:6699, in Index.drop(self, labels, errors)
   6697 if mask.any():
   6698     if errors != "ignore":
-&gt; 6699         raise KeyError(f"{list(labels[mask])} not found in axis")
   6700     indexer = indexer[~mask]
   6701 return self.delete(indexer)

KeyError: "['scmType', 'repositoryLink'] not found in axis"```


[Slack Message](https://moderneinc.slack.com/archives/C01S4M53THT/p1729566087494899?thread_ts=1729565466.378169&cid=C01S4M53THT)

**Comment by zieka** [comment]
did we remove or change how those columns get populated in services?

looks like they are still there 
https://github.com/moderneinc/moderne-recipe-execution/blob/f908956c85c71c469c90b32791241961bb961def/src/main/java/io/moderne/recipeexec/DataTableService.java#L408-L409

maybe download datatable from that run and see if its present

**Comment by sjungling** [comment]
@zieka I did download the data table, the columns were present, and when I copied the content from the data table to the `moderne-visualizations-misc` repo to use as the mock data for that particular visualization, it worked fine in VSCode with python 3.11 as the kernel version.

**Comment by zieka** [comment]
I made a small change right now that might help:
https://github.com/moderneinc/moderne-visualizations-misc/commit/c4ed15d1a4d225c6f9f9a03a6fc81f96dbc7051f

**Comment by sjungling** [comment]
cool. let's publish it
